/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated/admin/templates'
import { Route as AuthenticatedAdminTemplateTypesRouteImport } from './routes/_authenticated/admin/template-types'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminFeaturedItemsRouteImport } from './routes/_authenticated/admin/featured-items'
import { Route as AuthenticatedAdminConfigsRouteImport } from './routes/_authenticated/admin/configs'
import { Route as AuthenticatedAdminLegalTypeRouteRouteImport } from './routes/_authenticated/admin/legal/$type/route'
import { Route as AuthenticatedAdminLegalTypeIndexRouteImport } from './routes/_authenticated/admin/legal/$type/index'
import { Route as AuthenticatedAdminLegalTypeVersionsRouteImport } from './routes/_authenticated/admin/legal/$type/versions'
import { Route as AuthenticatedAdminLegalTypeCreateRouteImport } from './routes/_authenticated/admin/legal/$type/create'
import { Route as AuthenticatedAdminLegalTypeIdRouteImport } from './routes/_authenticated/admin/legal/$type/$id'
import { Route as AuthenticatedAdminLegalTypeIdEditRouteImport } from './routes/_authenticated/admin/legal/$type/$id.edit'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplateTypesRoute =
  AuthenticatedAdminTemplateTypesRouteImport.update({
    id: '/template-types',
    path: '/template-types',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFeaturedItemsRoute =
  AuthenticatedAdminFeaturedItemsRouteImport.update({
    id: '/featured-items',
    path: '/featured-items',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfigsRoute =
  AuthenticatedAdminConfigsRouteImport.update({
    id: '/configs',
    path: '/configs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLegalTypeRouteRoute =
  AuthenticatedAdminLegalTypeRouteRouteImport.update({
    id: '/legal/$type',
    path: '/legal/$type',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLegalTypeIndexRoute =
  AuthenticatedAdminLegalTypeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminLegalTypeRouteRoute,
  } as any)
const AuthenticatedAdminLegalTypeVersionsRoute =
  AuthenticatedAdminLegalTypeVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAdminLegalTypeRouteRoute,
  } as any)
const AuthenticatedAdminLegalTypeCreateRoute =
  AuthenticatedAdminLegalTypeCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdminLegalTypeRouteRoute,
  } as any)
const AuthenticatedAdminLegalTypeIdRoute =
  AuthenticatedAdminLegalTypeIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminLegalTypeRouteRoute,
  } as any)
const AuthenticatedAdminLegalTypeIdEditRoute =
  AuthenticatedAdminLegalTypeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdminLegalTypeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/configs': typeof AuthenticatedAdminConfigsRoute
  '/admin/featured-items': typeof AuthenticatedAdminFeaturedItemsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/template-types': typeof AuthenticatedAdminTemplateTypesRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/legal/$type': typeof AuthenticatedAdminLegalTypeRouteRouteWithChildren
  '/admin/legal/$type/$id': typeof AuthenticatedAdminLegalTypeIdRouteWithChildren
  '/admin/legal/$type/create': typeof AuthenticatedAdminLegalTypeCreateRoute
  '/admin/legal/$type/versions': typeof AuthenticatedAdminLegalTypeVersionsRoute
  '/admin/legal/$type/': typeof AuthenticatedAdminLegalTypeIndexRoute
  '/admin/legal/$type/$id/edit': typeof AuthenticatedAdminLegalTypeIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/configs': typeof AuthenticatedAdminConfigsRoute
  '/admin/featured-items': typeof AuthenticatedAdminFeaturedItemsRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/template-types': typeof AuthenticatedAdminTemplateTypesRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/legal/$type/$id': typeof AuthenticatedAdminLegalTypeIdRouteWithChildren
  '/admin/legal/$type/create': typeof AuthenticatedAdminLegalTypeCreateRoute
  '/admin/legal/$type/versions': typeof AuthenticatedAdminLegalTypeVersionsRoute
  '/admin/legal/$type': typeof AuthenticatedAdminLegalTypeIndexRoute
  '/admin/legal/$type/$id/edit': typeof AuthenticatedAdminLegalTypeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/configs': typeof AuthenticatedAdminConfigsRoute
  '/_authenticated/admin/featured-items': typeof AuthenticatedAdminFeaturedItemsRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/template-types': typeof AuthenticatedAdminTemplateTypesRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/legal/$type': typeof AuthenticatedAdminLegalTypeRouteRouteWithChildren
  '/_authenticated/admin/legal/$type/$id': typeof AuthenticatedAdminLegalTypeIdRouteWithChildren
  '/_authenticated/admin/legal/$type/create': typeof AuthenticatedAdminLegalTypeCreateRoute
  '/_authenticated/admin/legal/$type/versions': typeof AuthenticatedAdminLegalTypeVersionsRoute
  '/_authenticated/admin/legal/$type/': typeof AuthenticatedAdminLegalTypeIndexRoute
  '/_authenticated/admin/legal/$type/$id/edit': typeof AuthenticatedAdminLegalTypeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin/configs'
    | '/admin/featured-items'
    | '/admin/orders'
    | '/admin/tags'
    | '/admin/template-types'
    | '/admin/templates'
    | '/admin/users'
    | '/admin/'
    | '/admin/legal/$type'
    | '/admin/legal/$type/$id'
    | '/admin/legal/$type/create'
    | '/admin/legal/$type/versions'
    | '/admin/legal/$type/'
    | '/admin/legal/$type/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/admin/configs'
    | '/admin/featured-items'
    | '/admin/orders'
    | '/admin/tags'
    | '/admin/template-types'
    | '/admin/templates'
    | '/admin/users'
    | '/admin'
    | '/admin/legal/$type/$id'
    | '/admin/legal/$type/create'
    | '/admin/legal/$type/versions'
    | '/admin/legal/$type'
    | '/admin/legal/$type/$id/edit'
  id:
    | '__root__'
    | '/auth'
    | '/_authenticated'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/_authenticated/admin'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/'
    | '/_authenticated/admin/configs'
    | '/_authenticated/admin/featured-items'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/template-types'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/legal/$type'
    | '/_authenticated/admin/legal/$type/$id'
    | '/_authenticated/admin/legal/$type/create'
    | '/_authenticated/admin/legal/$type/versions'
    | '/_authenticated/admin/legal/$type/'
    | '/_authenticated/admin/legal/$type/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/template-types': {
      id: '/_authenticated/admin/template-types'
      path: '/template-types'
      fullPath: '/admin/template-types'
      preLoaderRoute: typeof AuthenticatedAdminTemplateTypesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/featured-items': {
      id: '/_authenticated/admin/featured-items'
      path: '/featured-items'
      fullPath: '/admin/featured-items'
      preLoaderRoute: typeof AuthenticatedAdminFeaturedItemsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configs': {
      id: '/_authenticated/admin/configs'
      path: '/configs'
      fullPath: '/admin/configs'
      preLoaderRoute: typeof AuthenticatedAdminConfigsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/legal/$type': {
      id: '/_authenticated/admin/legal/$type'
      path: '/legal/$type'
      fullPath: '/admin/legal/$type'
      preLoaderRoute: typeof AuthenticatedAdminLegalTypeRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/legal/$type/': {
      id: '/_authenticated/admin/legal/$type/'
      path: '/'
      fullPath: '/admin/legal/$type/'
      preLoaderRoute: typeof AuthenticatedAdminLegalTypeIndexRouteImport
      parentRoute: typeof AuthenticatedAdminLegalTypeRouteRoute
    }
    '/_authenticated/admin/legal/$type/versions': {
      id: '/_authenticated/admin/legal/$type/versions'
      path: '/versions'
      fullPath: '/admin/legal/$type/versions'
      preLoaderRoute: typeof AuthenticatedAdminLegalTypeVersionsRouteImport
      parentRoute: typeof AuthenticatedAdminLegalTypeRouteRoute
    }
    '/_authenticated/admin/legal/$type/create': {
      id: '/_authenticated/admin/legal/$type/create'
      path: '/create'
      fullPath: '/admin/legal/$type/create'
      preLoaderRoute: typeof AuthenticatedAdminLegalTypeCreateRouteImport
      parentRoute: typeof AuthenticatedAdminLegalTypeRouteRoute
    }
    '/_authenticated/admin/legal/$type/$id': {
      id: '/_authenticated/admin/legal/$type/$id'
      path: '/$id'
      fullPath: '/admin/legal/$type/$id'
      preLoaderRoute: typeof AuthenticatedAdminLegalTypeIdRouteImport
      parentRoute: typeof AuthenticatedAdminLegalTypeRouteRoute
    }
    '/_authenticated/admin/legal/$type/$id/edit': {
      id: '/_authenticated/admin/legal/$type/$id/edit'
      path: '/edit'
      fullPath: '/admin/legal/$type/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminLegalTypeIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminLegalTypeIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedAdminLegalTypeIdRouteChildren {
  AuthenticatedAdminLegalTypeIdEditRoute: typeof AuthenticatedAdminLegalTypeIdEditRoute
}

const AuthenticatedAdminLegalTypeIdRouteChildren: AuthenticatedAdminLegalTypeIdRouteChildren =
  {
    AuthenticatedAdminLegalTypeIdEditRoute:
      AuthenticatedAdminLegalTypeIdEditRoute,
  }

const AuthenticatedAdminLegalTypeIdRouteWithChildren =
  AuthenticatedAdminLegalTypeIdRoute._addFileChildren(
    AuthenticatedAdminLegalTypeIdRouteChildren,
  )

interface AuthenticatedAdminLegalTypeRouteRouteChildren {
  AuthenticatedAdminLegalTypeIdRoute: typeof AuthenticatedAdminLegalTypeIdRouteWithChildren
  AuthenticatedAdminLegalTypeCreateRoute: typeof AuthenticatedAdminLegalTypeCreateRoute
  AuthenticatedAdminLegalTypeVersionsRoute: typeof AuthenticatedAdminLegalTypeVersionsRoute
  AuthenticatedAdminLegalTypeIndexRoute: typeof AuthenticatedAdminLegalTypeIndexRoute
}

const AuthenticatedAdminLegalTypeRouteRouteChildren: AuthenticatedAdminLegalTypeRouteRouteChildren =
  {
    AuthenticatedAdminLegalTypeIdRoute:
      AuthenticatedAdminLegalTypeIdRouteWithChildren,
    AuthenticatedAdminLegalTypeCreateRoute:
      AuthenticatedAdminLegalTypeCreateRoute,
    AuthenticatedAdminLegalTypeVersionsRoute:
      AuthenticatedAdminLegalTypeVersionsRoute,
    AuthenticatedAdminLegalTypeIndexRoute:
      AuthenticatedAdminLegalTypeIndexRoute,
  }

const AuthenticatedAdminLegalTypeRouteRouteWithChildren =
  AuthenticatedAdminLegalTypeRouteRoute._addFileChildren(
    AuthenticatedAdminLegalTypeRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConfigsRoute: typeof AuthenticatedAdminConfigsRoute
  AuthenticatedAdminFeaturedItemsRoute: typeof AuthenticatedAdminFeaturedItemsRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminTemplateTypesRoute: typeof AuthenticatedAdminTemplateTypesRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminLegalTypeRouteRoute: typeof AuthenticatedAdminLegalTypeRouteRouteWithChildren
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConfigsRoute: AuthenticatedAdminConfigsRoute,
    AuthenticatedAdminFeaturedItemsRoute: AuthenticatedAdminFeaturedItemsRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
    AuthenticatedAdminTemplateTypesRoute: AuthenticatedAdminTemplateTypesRoute,
    AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminLegalTypeRouteRoute:
      AuthenticatedAdminLegalTypeRouteRouteWithChildren,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
