/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AuthenticatedCustomerRouteImport } from './routes/_authenticated/_customer'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/_checkout'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCustomerIndexRouteImport } from './routes/_authenticated/_customer/index'
import { Route as AuthenticatedAdminTemplateTypesRouteImport } from './routes/_authenticated/admin/template-types'
import { Route as AuthenticatedAdminConfigsRouteImport } from './routes/_authenticated/admin/configs'
import { Route as AuthenticatedAdminListingRouteImport } from './routes/_authenticated/admin/_listing'
import { Route as AuthenticatedCustomerTemplatesRouteImport } from './routes/_authenticated/_customer/templates'
import { Route as AuthenticatedCustomerMyCardsRouteImport } from './routes/_authenticated/_customer/my-cards'
import { Route as AuthenticatedCustomerCreateCardRouteImport } from './routes/_authenticated/_customer/create-card'
import { Route as AuthenticatedCustomerCartRouteImport } from './routes/_authenticated/_customer/cart'
import { Route as AuthenticatedCustomerAccountRouteImport } from './routes/_authenticated/_customer/account'
import { Route as AuthenticatedCheckoutCheckoutRouteImport } from './routes/_authenticated/_checkout/checkout'
import { Route as AuthenticatedAdminTemplatesCreateRouteImport } from './routes/_authenticated/admin/templates/create'
import { Route as AuthenticatedAdminListingTemplatesRouteImport } from './routes/_authenticated/admin/_listing/templates'
import { Route as AuthenticatedAdminListingTagsRouteImport } from './routes/_authenticated/admin/_listing/tags'
import { Route as AuthenticatedAdminListingOrdersRouteImport } from './routes/_authenticated/admin/_listing/orders'
import { Route as AuthenticatedAdminListingFeaturedItemsRouteImport } from './routes/_authenticated/admin/_listing/featured-items'
import { Route as AuthenticatedAdminListingColorPresetsRouteImport } from './routes/_authenticated/admin/_listing/color-presets'
import { Route as AuthenticatedAdminListingColorLeaguesRouteImport } from './routes/_authenticated/admin/_listing/color-leagues'
import { Route as AuthenticatedAdminListingBatchesRouteImport } from './routes/_authenticated/admin/_listing/batches'
import { Route as AuthenticatedCustomerOrderSuccessOrderIdRouteImport } from './routes/_authenticated/_customer/order-success.$orderId'
import { Route as AuthenticatedAdmin_legalTypeRouteRouteImport } from './routes/_authenticated/admin/__legal/$type/route'
import { Route as AuthenticatedAdminTemplatesIdIndexRouteImport } from './routes/_authenticated/admin/templates/$id/index'
import { Route as AuthenticatedAdminTagsIdIndexRouteImport } from './routes/_authenticated/admin/tags/$id/index'
import { Route as AuthenticatedAdminBatchesBatchIdIndexRouteImport } from './routes/_authenticated/admin/batches/$batchId/index'
import { Route as AuthenticatedAdminListingUsersIndexRouteImport } from './routes/_authenticated/admin/_listing/users/index'
import { Route as AuthenticatedAdminTemplatesIdEditRouteImport } from './routes/_authenticated/admin/templates/$id/edit'
import { Route as AuthenticatedAdminListing_legalTypeRouteImport } from './routes/_authenticated/admin/_listing/__legal.$type'
import { Route as AuthenticatedAdmin_legalTypeVersionsRouteImport } from './routes/_authenticated/admin/__legal/$type/versions'
import { Route as AuthenticatedAdmin_legalTypeCreateRouteImport } from './routes/_authenticated/admin/__legal/$type/create'
import { Route as AuthenticatedAdmin_legalTypeIdRouteRouteImport } from './routes/_authenticated/admin/__legal/$type/$id/route'
import { Route as AuthenticatedAdminListingUsersIdIndexRouteImport } from './routes/_authenticated/admin/_listing/users/$id/index'
import { Route as AuthenticatedAdmin_legalTypeIdIndexRouteImport } from './routes/_authenticated/admin/__legal/$type/$id/index'
import { Route as AuthenticatedAdmin_legalTypeIdEditRouteImport } from './routes/_authenticated/admin/__legal/$type/$id/edit'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomerRoute = AuthenticatedCustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/_checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCustomerIndexRoute =
  AuthenticatedCustomerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedAdminTemplateTypesRoute =
  AuthenticatedAdminTemplateTypesRouteImport.update({
    id: '/template-types',
    path: '/template-types',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfigsRoute =
  AuthenticatedAdminConfigsRouteImport.update({
    id: '/configs',
    path: '/configs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminListingRoute =
  AuthenticatedAdminListingRouteImport.update({
    id: '/_listing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCustomerTemplatesRoute =
  AuthenticatedCustomerTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedCustomerMyCardsRoute =
  AuthenticatedCustomerMyCardsRouteImport.update({
    id: '/my-cards',
    path: '/my-cards',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedCustomerCreateCardRoute =
  AuthenticatedCustomerCreateCardRouteImport.update({
    id: '/create-card',
    path: '/create-card',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedCustomerCartRoute =
  AuthenticatedCustomerCartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedCustomerAccountRoute =
  AuthenticatedCustomerAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedCheckoutCheckoutRoute =
  AuthenticatedCheckoutCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedAdminTemplatesCreateRoute =
  AuthenticatedAdminTemplatesCreateRouteImport.update({
    id: '/templates/create',
    path: '/templates/create',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminListingTemplatesRoute =
  AuthenticatedAdminListingTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminListingTagsRoute =
  AuthenticatedAdminListingTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminListingOrdersRoute =
  AuthenticatedAdminListingOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminListingFeaturedItemsRoute =
  AuthenticatedAdminListingFeaturedItemsRouteImport.update({
    id: '/featured-items',
    path: '/featured-items',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminListingColorPresetsRoute =
  AuthenticatedAdminListingColorPresetsRouteImport.update({
    id: '/color-presets',
    path: '/color-presets',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminListingColorLeaguesRoute =
  AuthenticatedAdminListingColorLeaguesRouteImport.update({
    id: '/color-leagues',
    path: '/color-leagues',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminListingBatchesRoute =
  AuthenticatedAdminListingBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedCustomerOrderSuccessOrderIdRoute =
  AuthenticatedCustomerOrderSuccessOrderIdRouteImport.update({
    id: '/order-success/$orderId',
    path: '/order-success/$orderId',
    getParentRoute: () => AuthenticatedCustomerRoute,
  } as any)
const AuthenticatedAdmin_legalTypeRouteRoute =
  AuthenticatedAdmin_legalTypeRouteRouteImport.update({
    id: '/__legal/$type',
    path: '/$type',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTemplatesIdIndexRoute =
  AuthenticatedAdminTemplatesIdIndexRouteImport.update({
    id: '/templates/$id/',
    path: '/templates/$id/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTagsIdIndexRoute =
  AuthenticatedAdminTagsIdIndexRouteImport.update({
    id: '/tags/$id/',
    path: '/tags/$id/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBatchesBatchIdIndexRoute =
  AuthenticatedAdminBatchesBatchIdIndexRouteImport.update({
    id: '/batches/$batchId/',
    path: '/batches/$batchId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminListingUsersIndexRoute =
  AuthenticatedAdminListingUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdminTemplatesIdEditRoute =
  AuthenticatedAdminTemplatesIdEditRouteImport.update({
    id: '/templates/$id/edit',
    path: '/templates/$id/edit',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminListing_legalTypeRoute =
  AuthenticatedAdminListing_legalTypeRouteImport.update({
    id: '/__legal/$type',
    path: '/$type',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdmin_legalTypeVersionsRoute =
  AuthenticatedAdmin_legalTypeVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAdmin_legalTypeRouteRoute,
  } as any)
const AuthenticatedAdmin_legalTypeCreateRoute =
  AuthenticatedAdmin_legalTypeCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAdmin_legalTypeRouteRoute,
  } as any)
const AuthenticatedAdmin_legalTypeIdRouteRoute =
  AuthenticatedAdmin_legalTypeIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdmin_legalTypeRouteRoute,
  } as any)
const AuthenticatedAdminListingUsersIdIndexRoute =
  AuthenticatedAdminListingUsersIdIndexRouteImport.update({
    id: '/users/$id/',
    path: '/users/$id/',
    getParentRoute: () => AuthenticatedAdminListingRoute,
  } as any)
const AuthenticatedAdmin_legalTypeIdIndexRoute =
  AuthenticatedAdmin_legalTypeIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdmin_legalTypeIdRouteRoute,
  } as any)
const AuthenticatedAdmin_legalTypeIdEditRoute =
  AuthenticatedAdmin_legalTypeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAdmin_legalTypeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin': typeof AuthenticatedAdminListingRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/checkout': typeof AuthenticatedCheckoutCheckoutRoute
  '/account': typeof AuthenticatedCustomerAccountRoute
  '/cart': typeof AuthenticatedCustomerCartRoute
  '/create-card': typeof AuthenticatedCustomerCreateCardRoute
  '/my-cards': typeof AuthenticatedCustomerMyCardsRoute
  '/templates': typeof AuthenticatedCustomerTemplatesRoute
  '/admin/configs': typeof AuthenticatedAdminConfigsRoute
  '/admin/template-types': typeof AuthenticatedAdminTemplateTypesRoute
  '/': typeof AuthenticatedCustomerIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/$type': typeof AuthenticatedAdminListing_legalTypeRoute
  '/order-success/$orderId': typeof AuthenticatedCustomerOrderSuccessOrderIdRoute
  '/admin/batches': typeof AuthenticatedAdminListingBatchesRoute
  '/admin/color-leagues': typeof AuthenticatedAdminListingColorLeaguesRoute
  '/admin/color-presets': typeof AuthenticatedAdminListingColorPresetsRoute
  '/admin/featured-items': typeof AuthenticatedAdminListingFeaturedItemsRoute
  '/admin/orders': typeof AuthenticatedAdminListingOrdersRoute
  '/admin/tags': typeof AuthenticatedAdminListingTagsRoute
  '/admin/templates': typeof AuthenticatedAdminListingTemplatesRoute
  '/admin/templates/create': typeof AuthenticatedAdminTemplatesCreateRoute
  '/admin/$type/$id': typeof AuthenticatedAdmin_legalTypeIdRouteRouteWithChildren
  '/admin/$type/create': typeof AuthenticatedAdmin_legalTypeCreateRoute
  '/admin/$type/versions': typeof AuthenticatedAdmin_legalTypeVersionsRoute
  '/admin/templates/$id/edit': typeof AuthenticatedAdminTemplatesIdEditRoute
  '/admin/users': typeof AuthenticatedAdminListingUsersIndexRoute
  '/admin/batches/$batchId': typeof AuthenticatedAdminBatchesBatchIdIndexRoute
  '/admin/tags/$id': typeof AuthenticatedAdminTagsIdIndexRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdIndexRoute
  '/admin/$type/$id/edit': typeof AuthenticatedAdmin_legalTypeIdEditRoute
  '/admin/$type/$id/': typeof AuthenticatedAdmin_legalTypeIdIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminListingUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout': typeof AuthenticatedCheckoutCheckoutRoute
  '/account': typeof AuthenticatedCustomerAccountRoute
  '/cart': typeof AuthenticatedCustomerCartRoute
  '/create-card': typeof AuthenticatedCustomerCreateCardRoute
  '/my-cards': typeof AuthenticatedCustomerMyCardsRoute
  '/templates': typeof AuthenticatedCustomerTemplatesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/configs': typeof AuthenticatedAdminConfigsRoute
  '/admin/template-types': typeof AuthenticatedAdminTemplateTypesRoute
  '/': typeof AuthenticatedCustomerIndexRoute
  '/admin/$type': typeof AuthenticatedAdminListing_legalTypeRoute
  '/order-success/$orderId': typeof AuthenticatedCustomerOrderSuccessOrderIdRoute
  '/admin/batches': typeof AuthenticatedAdminListingBatchesRoute
  '/admin/color-leagues': typeof AuthenticatedAdminListingColorLeaguesRoute
  '/admin/color-presets': typeof AuthenticatedAdminListingColorPresetsRoute
  '/admin/featured-items': typeof AuthenticatedAdminListingFeaturedItemsRoute
  '/admin/orders': typeof AuthenticatedAdminListingOrdersRoute
  '/admin/tags': typeof AuthenticatedAdminListingTagsRoute
  '/admin/templates': typeof AuthenticatedAdminListingTemplatesRoute
  '/admin/templates/create': typeof AuthenticatedAdminTemplatesCreateRoute
  '/admin/$type/create': typeof AuthenticatedAdmin_legalTypeCreateRoute
  '/admin/$type/versions': typeof AuthenticatedAdmin_legalTypeVersionsRoute
  '/admin/templates/$id/edit': typeof AuthenticatedAdminTemplatesIdEditRoute
  '/admin/users': typeof AuthenticatedAdminListingUsersIndexRoute
  '/admin/batches/$batchId': typeof AuthenticatedAdminBatchesBatchIdIndexRoute
  '/admin/tags/$id': typeof AuthenticatedAdminTagsIdIndexRoute
  '/admin/templates/$id': typeof AuthenticatedAdminTemplatesIdIndexRoute
  '/admin/$type/$id/edit': typeof AuthenticatedAdmin_legalTypeIdEditRoute
  '/admin/$type/$id': typeof AuthenticatedAdmin_legalTypeIdIndexRoute
  '/admin/users/$id': typeof AuthenticatedAdminListingUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/_authenticated/_customer': typeof AuthenticatedCustomerRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/_checkout/checkout': typeof AuthenticatedCheckoutCheckoutRoute
  '/_authenticated/_customer/account': typeof AuthenticatedCustomerAccountRoute
  '/_authenticated/_customer/cart': typeof AuthenticatedCustomerCartRoute
  '/_authenticated/_customer/create-card': typeof AuthenticatedCustomerCreateCardRoute
  '/_authenticated/_customer/my-cards': typeof AuthenticatedCustomerMyCardsRoute
  '/_authenticated/_customer/templates': typeof AuthenticatedCustomerTemplatesRoute
  '/_authenticated/admin/_listing': typeof AuthenticatedAdminListingRouteWithChildren
  '/_authenticated/admin/configs': typeof AuthenticatedAdminConfigsRoute
  '/_authenticated/admin/template-types': typeof AuthenticatedAdminTemplateTypesRoute
  '/_authenticated/_customer/': typeof AuthenticatedCustomerIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/__legal/$type': typeof AuthenticatedAdmin_legalTypeRouteRouteWithChildren
  '/_authenticated/_customer/order-success/$orderId': typeof AuthenticatedCustomerOrderSuccessOrderIdRoute
  '/_authenticated/admin/_listing/batches': typeof AuthenticatedAdminListingBatchesRoute
  '/_authenticated/admin/_listing/color-leagues': typeof AuthenticatedAdminListingColorLeaguesRoute
  '/_authenticated/admin/_listing/color-presets': typeof AuthenticatedAdminListingColorPresetsRoute
  '/_authenticated/admin/_listing/featured-items': typeof AuthenticatedAdminListingFeaturedItemsRoute
  '/_authenticated/admin/_listing/orders': typeof AuthenticatedAdminListingOrdersRoute
  '/_authenticated/admin/_listing/tags': typeof AuthenticatedAdminListingTagsRoute
  '/_authenticated/admin/_listing/templates': typeof AuthenticatedAdminListingTemplatesRoute
  '/_authenticated/admin/templates/create': typeof AuthenticatedAdminTemplatesCreateRoute
  '/_authenticated/admin/__legal/$type/$id': typeof AuthenticatedAdmin_legalTypeIdRouteRouteWithChildren
  '/_authenticated/admin/__legal/$type/create': typeof AuthenticatedAdmin_legalTypeCreateRoute
  '/_authenticated/admin/__legal/$type/versions': typeof AuthenticatedAdmin_legalTypeVersionsRoute
  '/_authenticated/admin/_listing/__legal/$type': typeof AuthenticatedAdminListing_legalTypeRoute
  '/_authenticated/admin/templates/$id/edit': typeof AuthenticatedAdminTemplatesIdEditRoute
  '/_authenticated/admin/_listing/users/': typeof AuthenticatedAdminListingUsersIndexRoute
  '/_authenticated/admin/batches/$batchId/': typeof AuthenticatedAdminBatchesBatchIdIndexRoute
  '/_authenticated/admin/tags/$id/': typeof AuthenticatedAdminTagsIdIndexRoute
  '/_authenticated/admin/templates/$id/': typeof AuthenticatedAdminTemplatesIdIndexRoute
  '/_authenticated/admin/__legal/$type/$id/edit': typeof AuthenticatedAdmin_legalTypeIdEditRoute
  '/_authenticated/admin/__legal/$type/$id/': typeof AuthenticatedAdmin_legalTypeIdIndexRoute
  '/_authenticated/admin/_listing/users/$id/': typeof AuthenticatedAdminListingUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin'
    | '/admin/login'
    | '/checkout'
    | '/account'
    | '/cart'
    | '/create-card'
    | '/my-cards'
    | '/templates'
    | '/admin/configs'
    | '/admin/template-types'
    | '/'
    | '/admin/'
    | '/admin/$type'
    | '/order-success/$orderId'
    | '/admin/batches'
    | '/admin/color-leagues'
    | '/admin/color-presets'
    | '/admin/featured-items'
    | '/admin/orders'
    | '/admin/tags'
    | '/admin/templates'
    | '/admin/templates/create'
    | '/admin/$type/$id'
    | '/admin/$type/create'
    | '/admin/$type/versions'
    | '/admin/templates/$id/edit'
    | '/admin/users'
    | '/admin/batches/$batchId'
    | '/admin/tags/$id'
    | '/admin/templates/$id'
    | '/admin/$type/$id/edit'
    | '/admin/$type/$id/'
    | '/admin/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/login'
    | '/checkout'
    | '/account'
    | '/cart'
    | '/create-card'
    | '/my-cards'
    | '/templates'
    | '/admin'
    | '/admin/configs'
    | '/admin/template-types'
    | '/'
    | '/admin/$type'
    | '/order-success/$orderId'
    | '/admin/batches'
    | '/admin/color-leagues'
    | '/admin/color-presets'
    | '/admin/featured-items'
    | '/admin/orders'
    | '/admin/tags'
    | '/admin/templates'
    | '/admin/templates/create'
    | '/admin/$type/create'
    | '/admin/$type/versions'
    | '/admin/templates/$id/edit'
    | '/admin/users'
    | '/admin/batches/$batchId'
    | '/admin/tags/$id'
    | '/admin/templates/$id'
    | '/admin/$type/$id/edit'
    | '/admin/$type/$id'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/_authenticated/admin'
    | '/_authenticated/_checkout'
    | '/_authenticated/_customer'
    | '/admin/login'
    | '/_authenticated/_checkout/checkout'
    | '/_authenticated/_customer/account'
    | '/_authenticated/_customer/cart'
    | '/_authenticated/_customer/create-card'
    | '/_authenticated/_customer/my-cards'
    | '/_authenticated/_customer/templates'
    | '/_authenticated/admin/_listing'
    | '/_authenticated/admin/configs'
    | '/_authenticated/admin/template-types'
    | '/_authenticated/_customer/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/__legal/$type'
    | '/_authenticated/_customer/order-success/$orderId'
    | '/_authenticated/admin/_listing/batches'
    | '/_authenticated/admin/_listing/color-leagues'
    | '/_authenticated/admin/_listing/color-presets'
    | '/_authenticated/admin/_listing/featured-items'
    | '/_authenticated/admin/_listing/orders'
    | '/_authenticated/admin/_listing/tags'
    | '/_authenticated/admin/_listing/templates'
    | '/_authenticated/admin/templates/create'
    | '/_authenticated/admin/__legal/$type/$id'
    | '/_authenticated/admin/__legal/$type/create'
    | '/_authenticated/admin/__legal/$type/versions'
    | '/_authenticated/admin/_listing/__legal/$type'
    | '/_authenticated/admin/templates/$id/edit'
    | '/_authenticated/admin/_listing/users/'
    | '/_authenticated/admin/batches/$batchId/'
    | '/_authenticated/admin/tags/$id/'
    | '/_authenticated/admin/templates/$id/'
    | '/_authenticated/admin/__legal/$type/$id/edit'
    | '/_authenticated/admin/__legal/$type/$id/'
    | '/_authenticated/admin/_listing/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_customer': {
      id: '/_authenticated/_customer'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedCustomerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_checkout': {
      id: '/_authenticated/_checkout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_customer/': {
      id: '/_authenticated/_customer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/admin/template-types': {
      id: '/_authenticated/admin/template-types'
      path: '/template-types'
      fullPath: '/admin/template-types'
      preLoaderRoute: typeof AuthenticatedAdminTemplateTypesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configs': {
      id: '/_authenticated/admin/configs'
      path: '/configs'
      fullPath: '/admin/configs'
      preLoaderRoute: typeof AuthenticatedAdminConfigsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/_listing': {
      id: '/_authenticated/admin/_listing'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminListingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_customer/templates': {
      id: '/_authenticated/_customer/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedCustomerTemplatesRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/_customer/my-cards': {
      id: '/_authenticated/_customer/my-cards'
      path: '/my-cards'
      fullPath: '/my-cards'
      preLoaderRoute: typeof AuthenticatedCustomerMyCardsRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/_customer/create-card': {
      id: '/_authenticated/_customer/create-card'
      path: '/create-card'
      fullPath: '/create-card'
      preLoaderRoute: typeof AuthenticatedCustomerCreateCardRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/_customer/cart': {
      id: '/_authenticated/_customer/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCustomerCartRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/_customer/account': {
      id: '/_authenticated/_customer/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedCustomerAccountRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/_checkout/checkout': {
      id: '/_authenticated/_checkout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutCheckoutRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/admin/templates/create': {
      id: '/_authenticated/admin/templates/create'
      path: '/templates/create'
      fullPath: '/admin/templates/create'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesCreateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/_listing/templates': {
      id: '/_authenticated/admin/_listing/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminListingTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/_listing/tags': {
      id: '/_authenticated/admin/_listing/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminListingTagsRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/_listing/orders': {
      id: '/_authenticated/admin/_listing/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminListingOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/_listing/featured-items': {
      id: '/_authenticated/admin/_listing/featured-items'
      path: '/featured-items'
      fullPath: '/admin/featured-items'
      preLoaderRoute: typeof AuthenticatedAdminListingFeaturedItemsRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/_listing/color-presets': {
      id: '/_authenticated/admin/_listing/color-presets'
      path: '/color-presets'
      fullPath: '/admin/color-presets'
      preLoaderRoute: typeof AuthenticatedAdminListingColorPresetsRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/_listing/color-leagues': {
      id: '/_authenticated/admin/_listing/color-leagues'
      path: '/color-leagues'
      fullPath: '/admin/color-leagues'
      preLoaderRoute: typeof AuthenticatedAdminListingColorLeaguesRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/_listing/batches': {
      id: '/_authenticated/admin/_listing/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AuthenticatedAdminListingBatchesRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/_customer/order-success/$orderId': {
      id: '/_authenticated/_customer/order-success/$orderId'
      path: '/order-success/$orderId'
      fullPath: '/order-success/$orderId'
      preLoaderRoute: typeof AuthenticatedCustomerOrderSuccessOrderIdRouteImport
      parentRoute: typeof AuthenticatedCustomerRoute
    }
    '/_authenticated/admin/__legal/$type': {
      id: '/_authenticated/admin/__legal/$type'
      path: '/$type'
      fullPath: '/admin/$type'
      preLoaderRoute: typeof AuthenticatedAdmin_legalTypeRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/templates/$id/': {
      id: '/_authenticated/admin/templates/$id/'
      path: '/templates/$id'
      fullPath: '/admin/templates/$id'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tags/$id/': {
      id: '/_authenticated/admin/tags/$id/'
      path: '/tags/$id'
      fullPath: '/admin/tags/$id'
      preLoaderRoute: typeof AuthenticatedAdminTagsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/batches/$batchId/': {
      id: '/_authenticated/admin/batches/$batchId/'
      path: '/batches/$batchId'
      fullPath: '/admin/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedAdminBatchesBatchIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/_listing/users/': {
      id: '/_authenticated/admin/_listing/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminListingUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/templates/$id/edit': {
      id: '/_authenticated/admin/templates/$id/edit'
      path: '/templates/$id/edit'
      fullPath: '/admin/templates/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/_listing/__legal/$type': {
      id: '/_authenticated/admin/_listing/__legal/$type'
      path: '/$type'
      fullPath: '/admin/$type'
      preLoaderRoute: typeof AuthenticatedAdminListing_legalTypeRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/__legal/$type/versions': {
      id: '/_authenticated/admin/__legal/$type/versions'
      path: '/versions'
      fullPath: '/admin/$type/versions'
      preLoaderRoute: typeof AuthenticatedAdmin_legalTypeVersionsRouteImport
      parentRoute: typeof AuthenticatedAdmin_legalTypeRouteRoute
    }
    '/_authenticated/admin/__legal/$type/create': {
      id: '/_authenticated/admin/__legal/$type/create'
      path: '/create'
      fullPath: '/admin/$type/create'
      preLoaderRoute: typeof AuthenticatedAdmin_legalTypeCreateRouteImport
      parentRoute: typeof AuthenticatedAdmin_legalTypeRouteRoute
    }
    '/_authenticated/admin/__legal/$type/$id': {
      id: '/_authenticated/admin/__legal/$type/$id'
      path: '/$id'
      fullPath: '/admin/$type/$id'
      preLoaderRoute: typeof AuthenticatedAdmin_legalTypeIdRouteRouteImport
      parentRoute: typeof AuthenticatedAdmin_legalTypeRouteRoute
    }
    '/_authenticated/admin/_listing/users/$id/': {
      id: '/_authenticated/admin/_listing/users/$id/'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthenticatedAdminListingUsersIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminListingRoute
    }
    '/_authenticated/admin/__legal/$type/$id/': {
      id: '/_authenticated/admin/__legal/$type/$id/'
      path: '/'
      fullPath: '/admin/$type/$id/'
      preLoaderRoute: typeof AuthenticatedAdmin_legalTypeIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdmin_legalTypeIdRouteRoute
    }
    '/_authenticated/admin/__legal/$type/$id/edit': {
      id: '/_authenticated/admin/__legal/$type/$id/edit'
      path: '/edit'
      fullPath: '/admin/$type/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdmin_legalTypeIdEditRouteImport
      parentRoute: typeof AuthenticatedAdmin_legalTypeIdRouteRoute
    }
  }
}

interface AuthenticatedAdminListingRouteChildren {
  AuthenticatedAdminListingBatchesRoute: typeof AuthenticatedAdminListingBatchesRoute
  AuthenticatedAdminListingColorLeaguesRoute: typeof AuthenticatedAdminListingColorLeaguesRoute
  AuthenticatedAdminListingColorPresetsRoute: typeof AuthenticatedAdminListingColorPresetsRoute
  AuthenticatedAdminListingFeaturedItemsRoute: typeof AuthenticatedAdminListingFeaturedItemsRoute
  AuthenticatedAdminListingOrdersRoute: typeof AuthenticatedAdminListingOrdersRoute
  AuthenticatedAdminListingTagsRoute: typeof AuthenticatedAdminListingTagsRoute
  AuthenticatedAdminListingTemplatesRoute: typeof AuthenticatedAdminListingTemplatesRoute
  AuthenticatedAdminListing_legalTypeRoute: typeof AuthenticatedAdminListing_legalTypeRoute
  AuthenticatedAdminListingUsersIndexRoute: typeof AuthenticatedAdminListingUsersIndexRoute
  AuthenticatedAdminListingUsersIdIndexRoute: typeof AuthenticatedAdminListingUsersIdIndexRoute
}

const AuthenticatedAdminListingRouteChildren: AuthenticatedAdminListingRouteChildren =
  {
    AuthenticatedAdminListingBatchesRoute:
      AuthenticatedAdminListingBatchesRoute,
    AuthenticatedAdminListingColorLeaguesRoute:
      AuthenticatedAdminListingColorLeaguesRoute,
    AuthenticatedAdminListingColorPresetsRoute:
      AuthenticatedAdminListingColorPresetsRoute,
    AuthenticatedAdminListingFeaturedItemsRoute:
      AuthenticatedAdminListingFeaturedItemsRoute,
    AuthenticatedAdminListingOrdersRoute: AuthenticatedAdminListingOrdersRoute,
    AuthenticatedAdminListingTagsRoute: AuthenticatedAdminListingTagsRoute,
    AuthenticatedAdminListingTemplatesRoute:
      AuthenticatedAdminListingTemplatesRoute,
    AuthenticatedAdminListing_legalTypeRoute:
      AuthenticatedAdminListing_legalTypeRoute,
    AuthenticatedAdminListingUsersIndexRoute:
      AuthenticatedAdminListingUsersIndexRoute,
    AuthenticatedAdminListingUsersIdIndexRoute:
      AuthenticatedAdminListingUsersIdIndexRoute,
  }

const AuthenticatedAdminListingRouteWithChildren =
  AuthenticatedAdminListingRoute._addFileChildren(
    AuthenticatedAdminListingRouteChildren,
  )

interface AuthenticatedAdmin_legalTypeIdRouteRouteChildren {
  AuthenticatedAdmin_legalTypeIdEditRoute: typeof AuthenticatedAdmin_legalTypeIdEditRoute
  AuthenticatedAdmin_legalTypeIdIndexRoute: typeof AuthenticatedAdmin_legalTypeIdIndexRoute
}

const AuthenticatedAdmin_legalTypeIdRouteRouteChildren: AuthenticatedAdmin_legalTypeIdRouteRouteChildren =
  {
    AuthenticatedAdmin_legalTypeIdEditRoute:
      AuthenticatedAdmin_legalTypeIdEditRoute,
    AuthenticatedAdmin_legalTypeIdIndexRoute:
      AuthenticatedAdmin_legalTypeIdIndexRoute,
  }

const AuthenticatedAdmin_legalTypeIdRouteRouteWithChildren =
  AuthenticatedAdmin_legalTypeIdRouteRoute._addFileChildren(
    AuthenticatedAdmin_legalTypeIdRouteRouteChildren,
  )

interface AuthenticatedAdmin_legalTypeRouteRouteChildren {
  AuthenticatedAdmin_legalTypeIdRouteRoute: typeof AuthenticatedAdmin_legalTypeIdRouteRouteWithChildren
  AuthenticatedAdmin_legalTypeCreateRoute: typeof AuthenticatedAdmin_legalTypeCreateRoute
  AuthenticatedAdmin_legalTypeVersionsRoute: typeof AuthenticatedAdmin_legalTypeVersionsRoute
}

const AuthenticatedAdmin_legalTypeRouteRouteChildren: AuthenticatedAdmin_legalTypeRouteRouteChildren =
  {
    AuthenticatedAdmin_legalTypeIdRouteRoute:
      AuthenticatedAdmin_legalTypeIdRouteRouteWithChildren,
    AuthenticatedAdmin_legalTypeCreateRoute:
      AuthenticatedAdmin_legalTypeCreateRoute,
    AuthenticatedAdmin_legalTypeVersionsRoute:
      AuthenticatedAdmin_legalTypeVersionsRoute,
  }

const AuthenticatedAdmin_legalTypeRouteRouteWithChildren =
  AuthenticatedAdmin_legalTypeRouteRoute._addFileChildren(
    AuthenticatedAdmin_legalTypeRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminListingRoute: typeof AuthenticatedAdminListingRouteWithChildren
  AuthenticatedAdminConfigsRoute: typeof AuthenticatedAdminConfigsRoute
  AuthenticatedAdminTemplateTypesRoute: typeof AuthenticatedAdminTemplateTypesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdmin_legalTypeRouteRoute: typeof AuthenticatedAdmin_legalTypeRouteRouteWithChildren
  AuthenticatedAdminTemplatesCreateRoute: typeof AuthenticatedAdminTemplatesCreateRoute
  AuthenticatedAdminTemplatesIdEditRoute: typeof AuthenticatedAdminTemplatesIdEditRoute
  AuthenticatedAdminBatchesBatchIdIndexRoute: typeof AuthenticatedAdminBatchesBatchIdIndexRoute
  AuthenticatedAdminTagsIdIndexRoute: typeof AuthenticatedAdminTagsIdIndexRoute
  AuthenticatedAdminTemplatesIdIndexRoute: typeof AuthenticatedAdminTemplatesIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminListingRoute: AuthenticatedAdminListingRouteWithChildren,
    AuthenticatedAdminConfigsRoute: AuthenticatedAdminConfigsRoute,
    AuthenticatedAdminTemplateTypesRoute: AuthenticatedAdminTemplateTypesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdmin_legalTypeRouteRoute:
      AuthenticatedAdmin_legalTypeRouteRouteWithChildren,
    AuthenticatedAdminTemplatesCreateRoute:
      AuthenticatedAdminTemplatesCreateRoute,
    AuthenticatedAdminTemplatesIdEditRoute:
      AuthenticatedAdminTemplatesIdEditRoute,
    AuthenticatedAdminBatchesBatchIdIndexRoute:
      AuthenticatedAdminBatchesBatchIdIndexRoute,
    AuthenticatedAdminTagsIdIndexRoute: AuthenticatedAdminTagsIdIndexRoute,
    AuthenticatedAdminTemplatesIdIndexRoute:
      AuthenticatedAdminTemplatesIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCheckoutRouteChildren {
  AuthenticatedCheckoutCheckoutRoute: typeof AuthenticatedCheckoutCheckoutRoute
}

const AuthenticatedCheckoutRouteChildren: AuthenticatedCheckoutRouteChildren = {
  AuthenticatedCheckoutCheckoutRoute: AuthenticatedCheckoutCheckoutRoute,
}

const AuthenticatedCheckoutRouteWithChildren =
  AuthenticatedCheckoutRoute._addFileChildren(
    AuthenticatedCheckoutRouteChildren,
  )

interface AuthenticatedCustomerRouteChildren {
  AuthenticatedCustomerAccountRoute: typeof AuthenticatedCustomerAccountRoute
  AuthenticatedCustomerCartRoute: typeof AuthenticatedCustomerCartRoute
  AuthenticatedCustomerCreateCardRoute: typeof AuthenticatedCustomerCreateCardRoute
  AuthenticatedCustomerMyCardsRoute: typeof AuthenticatedCustomerMyCardsRoute
  AuthenticatedCustomerTemplatesRoute: typeof AuthenticatedCustomerTemplatesRoute
  AuthenticatedCustomerIndexRoute: typeof AuthenticatedCustomerIndexRoute
  AuthenticatedCustomerOrderSuccessOrderIdRoute: typeof AuthenticatedCustomerOrderSuccessOrderIdRoute
}

const AuthenticatedCustomerRouteChildren: AuthenticatedCustomerRouteChildren = {
  AuthenticatedCustomerAccountRoute: AuthenticatedCustomerAccountRoute,
  AuthenticatedCustomerCartRoute: AuthenticatedCustomerCartRoute,
  AuthenticatedCustomerCreateCardRoute: AuthenticatedCustomerCreateCardRoute,
  AuthenticatedCustomerMyCardsRoute: AuthenticatedCustomerMyCardsRoute,
  AuthenticatedCustomerTemplatesRoute: AuthenticatedCustomerTemplatesRoute,
  AuthenticatedCustomerIndexRoute: AuthenticatedCustomerIndexRoute,
  AuthenticatedCustomerOrderSuccessOrderIdRoute:
    AuthenticatedCustomerOrderSuccessOrderIdRoute,
}

const AuthenticatedCustomerRouteWithChildren =
  AuthenticatedCustomerRoute._addFileChildren(
    AuthenticatedCustomerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRouteWithChildren
  AuthenticatedCustomerRoute: typeof AuthenticatedCustomerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRouteWithChildren,
  AuthenticatedCustomerRoute: AuthenticatedCustomerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
